version : '3.8'
services:
  ruoyi-nacos:
    container_name: ruoyi-nacos
    image: nacos/nacos-server:v2.0.4
    restart: always
#    build:
#      context: ./
#      dockerfile: dockerfile
    environment:
      - MODE=standalone
    volumes:
      - ./logs/:/home/nacos/logs
      - ./conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    depends_on:
      - ruoyi-mysql
    links:
      - ruoyi-mysql
    networks:
      - wdh-pmp
networks:
  wdh-pmp:
    external: true