# 基础镜像
FROM nginx
# author
MAINTAINER zhaosh

# 挂载目录
VOLUME /home/wdh/projects/wdh-ui
# 创建目录
RUN mkdir -p /home/wdh/projects/wdh-ui
# 指定路径
WORKDIR /home/wdh/projects/wdh-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/wdh/projects/wdh-ui
