# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER zhaosh

# 挂载目录
VOLUME /home/wdh
# 创建目录
RUN mkdir -p /home/wdh
# 指定路径
WORKDIR /home/wdh
# 复制jar文件到路径
COPY ./jar/wdh-auth.jar /home/wdh/wdh-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","wdh-auth.jar"]