version : '3.8'
services:
  ruoyi-mysql:
    container_name: ruoyi-mysql
    image: mysql:5.7
    restart: always
#    build:
#      context: ./
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: password
    command: [
        'mysqld',
        '--innodb-buffer-pool-size=80M',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--max_connections=2000',
        '--default-time-zone=+8:00',
        '--lower-case-table-names=1'
    ]
    volumes:
#      - ./conf:/etc/mysql/conf.d
      - ./logs:/logs
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wdh-pmp
networks:
  wdh-pmp:
    external: true